---
output:
  bookdown::pdf_document2:
    toc: no
    number_sections: no
    pandoc_args: !expr rmdfiltr::add_wordcount_filter(rmdfiltr::add_citeproc_filter(args = NULL))
    latex_engine: xelatex
    keep_tex: yes
    #template: svm-latex-ms.tex
# output: 
#   pdf_document:
#     citation_package: natbib
#     keep_tex: true
#     fig_caption: true
#     latex_engine: pdflatex
#     template: svm-latex-ms.tex
header-includes:
  # - \usepackage{setspace}\doublespace
  # - \usepackage{endnotes}
  #- \let\footnote=\endnote
  #- \usepackage{endfloat}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \setlength{\headheight}{13.6pt}
  - \rhead{\textit{Hoffmann and Velasco}}
editor_options: 
  chunk_output_type: console
  
citeproc: no
fontfamily: mathpazo
fontsize: 11pt
geometry: margin=1in
indent: yes
link-citations: yes
linkcolor: blue
bibliography: zotero.bib  
csl: apa.csl

title: "Supplementary Material"
subtitle: "Making Migration Sexy"
date: "`r format(Sys.time(), '%B %e, %Y')`"
# author:
# - name: Nathan I. Hoffmann
#   affiliation: Department of Sociology, University of California, Los Angeles
# - name: Kristopher Velasco
#   affiliation: Department of Sociology, University of Texas at Austin
 
author:
- Nathan I. Hoffmann, Department of Sociology, University of California, Los Angeles
- Kristopher Velasco, Department of Sociology, University of Texas at Austin

---

<!-- Turn off hyphenation -->
<!-- \usepackage[none]{hyphenat} -->


```{r setup, include=F}
knitr::opts_chunk$set(echo = F, warning = F, message = F, cache = T, results = 'asis',
                      cache.lazy = F)

library(janitor)
library(priceR)
library(kableExtra)
library(sjstats)
library(imputeTS)
library(mvtnorm)
library(ordinal)
library(lme4)
library(MASS)
library(countrycode)
library(knitr)
library(RColorBrewer)
library(haven)
library(cowplot)
library(srvyr)
library(lmtest)
library(sandwich)
library(here)
library(plm)
library(stargazer)
library(tidyverse)

# knitr::opts_chunk$set(error=TRUE) 

options("yaml.eval.expr" = TRUE)

# theme_set(theme_cowplot(font_family = 'Palatino') + 
theme_set(theme_classic(base_family = 'Palatino') + 
            theme(legend.title=element_blank(), 
                  panel.grid.major.y = element_line('grey80'),
                  legend.background = element_rect(fill = "transparent")))
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Dark2") + 
  scale_fill_brewer(palette="Dark2")

options(scipen=1, digits=2)
knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",")
})
knitr::opts_chunk$set(error=TRUE) 


```

```{r load, include = F}
acs_wide <- read.csv(here('data', 'acs_wide.csv'))
acs_couple_policy <- readRDS(here('data', 'acs_couple_policy.rds'))
acs_prop_yrimmig_policy <- read.csv(here('data', 'acs_prop_yrimmig_policy.csv'))
acs_dyad_policy <- read.csv(here('data', 'acs_dyad_policy.csv'))

# acs_oneimm <- read.csv(here('data', 'acs_oneimm.csv'))
# acs_coupled_imms <- read.csv(here('data', 'acs_coupled_imms.csv'))
# acs_prop_yrimmig <- read.csv(here('data', 'acs_prop_yrimmig.csv'))
# acs_dyad <- read.csv(here('data', 'acs_dyad.csv'))




acs_wide_survey <- acs_wide %>% as_survey_design(ids = cluster, weights = hhwt)
acs_ind_survey <- acs_couple_policy %>% as_survey_design(ids = cluster, weights = perwt)


# Smaller dataset for initial ordered logit analyses
set.seed(1859)
acs_couple_policy_small <- bind_rows(
  filter(acs_couple_policy, same_sex == T),
  sample_n(filter(acs_couple_policy, same_sex == F), 1e5)
)


```

# Alternate country proportion specifications
```{r country-props}
# acs_prop_yrimmig_policy <- acs_prop_yrimmig_policy %>%
#   filter(yrimmig >= 1992)

# ag <- lm(I(log(n_same_sex+1)) ~ origin_score + I(log(n_total+1)), 
#          data = acs_prop_yrimmig_policy) 
# 
# 
# ag_country_orig <- lm(I(log(n_same_sex+1))  ~ distw + contig + comlang_off + comlang_ethno + colony +
#                    wage_dif + unemp_dif + polity5 + origin_score + stock_prop+ I(log(n_total+1)), 
#          data = acs_prop_yrimmig_policy)
# 
# ag_country_orig_fe <- lm(I(log(n_same_sex+1))  ~ distw + contig + comlang_off + comlang_ethno + colony +
#                    wage_dif + unemp_dif + polity5 + origin_score + stock_prop + bpld+ I(log(n_total+1)), 
#          data = acs_prop_yrimmig_policy)


# year of immigration fixed-effects
ag_country_time <- lm(prop_same_sex ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5 + origin_score + stock_prop + bpld + yrimmig,
         data = acs_prop_yrimmig_policy)

# Add binary indicator for post-2013
ag_country_orig_2013 <- lm(prop_same_sex ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5 + origin_score + stock_prop +
                     post_2013,
         data = mutate(acs_prop_yrimmig_policy, post_2013 = (yrimmig > 2013)))

# Interaction, no fixed effects
ag_2013_int <- lm(prop_same_sex ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5  + stock_prop + bpld +
                     post_2013*origin_score,
         data = mutate(acs_prop_yrimmig_policy, post_2013 = (yrimmig > 2013)))

# Spouse, no fixed effects
ag_2013_spouse1 <- lm(prop_spouse_same_sex ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5 + origin_score + stock_prop + 
                     post_2013,
         data = mutate(acs_prop_yrimmig_policy, post_2013 = (yrimmig > 2013)))

# Spouse, no interaction
ag_2013_spouse2 <- lm(prop_spouse_same_sex ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5 + origin_score + stock_prop + bpld +
                     post_2013,
         data = mutate(acs_prop_yrimmig_policy, post_2013 = (yrimmig > 2013)))



se_list <- list()
mod_list <- list(ag, ag_country_orig, ag_country_orig_fe, 
                 ag_country_orig_fe_2013, ag_2013_int_fe,
                 ag_2013_spouse, ag_2013_spouse_int)
for(mod_num in 1:length(mod_list)){
  se_list[[mod_num]] <- coef(summary(mod_list[[mod_num]], cluster = c("bpld")))[, 2]
}


stargazer(mod_list,
          header = F, 
          model.names = F,
          keep = c('origin_score', 'polity5', 'post_2013'),
          # omit = 'bpld',
          order = c('origin_score', 'polity5', 'post_2013', 'post_2013TRUE:origin_score'),
          # covariate.labels = c('Country LGBT policy score', 'Polity5 democratization',
          #                      'Post-2013', 'Country score × Post-2013'),
          dep.var.labels   = c("Percent in same-sex couples", "Married"),
          add.lines = list(c('Country controls?', 'no', rep('yes', 6)),
                           c('Country FEs?', 'no', 'no', rep('yes', 5))),
          se = se_list,
          keep.stat = c('n'),
          star.cutoffs = c(0.1, 0.05, 0.01, 0.001),
          star.char = c('†', '*', '**', '***'),
          notes = c("Note: †p<0.1; *p<0.05; **p<0.01; ***p<0.001", 
                    "Source: American Community Survey 2008-2019"), 
          notes.label = '',
          notes.align = 'l',
          notes.append = F,
          label = 'tab:country-props',
          title = 'OLS regressions of percent of immigrants in same-sex couples by year of immigration and country of origin. Country-clustered standard errors shown in parentheses. Country controls include population-weighted distance, contiguous border, common official language, common ethnic language, colonial relationship, wage differential, unemployment differential, proportion same-country stock, and Polity 5 measure of democratization.')

# One immigrant
ag_oneimm <- lm(prop_same_sex_oneimm ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5 + origin_score + stock_prop + bpld,
         data = acs_prop_yrimmig_policy)

ag_oneimm_2013 <- lm(prop_same_sex_oneimm ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5 + origin_score + stock_prop + bpld + post_2013*origin_score,
         data = mutate(acs_prop_yrimmig_policy, post_2013 = (yrimmig > 2013)))
```

# Adjusting proportions based on empirical mismatch rates
```{r country-props-2}
# acs_prop_yrimmig_policy <- acs_prop_yrimmig_policy %>%
#   filter(yrimmig >= 1992)

# ag <- lm(I(log(n_same_sex+1)) ~ origin_score + I(log(n_total+1)), 
#          data = acs_prop_yrimmig_policy) 
# 
# 
# ag_country_orig <- lm(I(log(n_same_sex+1))  ~ distw + contig + comlang_off + comlang_ethno + colony +
#                    wage_dif + unemp_dif + polity5 + origin_score + stock_prop+ I(log(n_total+1)), 
#          data = acs_prop_yrimmig_policy)
# 
# ag_country_orig_fe <- lm(I(log(n_same_sex+1))  ~ distw + contig + comlang_off + comlang_ethno + colony +
#                    wage_dif + unemp_dif + polity5 + origin_score + stock_prop + bpld+ I(log(n_total+1)), 
#          data = acs_prop_yrimmig_policy)



ag <- lm(prop_same_sex_adj ~ origin_score,
         data = acs_prop_yrimmig_policy)


ag_country_orig <- lm(prop_same_sex_adj ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5 + origin_score + stock_prop,
         data = acs_prop_yrimmig_policy)

ag_country_orig_fe <- lm(prop_same_sex_adj ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5 + origin_score + stock_prop + bpld,
         data = acs_prop_yrimmig_policy)

ag_oneimm <- lm(prop_same_sex_adj ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5 + origin_score + stock_prop + bpld,
         data = acs_prop_yrimmig_policy)

# Add binary indicator for post-2013
# ag_country_orig_2013 <- lm(prop_same_sex_adj ~ distw + contig + comlang_off + comlang_ethno + colony +
#                    wage_dif + unemp_dif + polity5 + origin_score + stock_prop +
#                      post_2013,
#          data = mutate(acs_prop_yrimmig_policy, post_2013 = (yrimmig > 2013)))

ag_country_orig_fe_2013 <- lm(prop_same_sex_adj ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5 + origin_score + stock_prop + bpld +
                     post_2013,
         data = mutate(acs_prop_yrimmig_policy, post_2013 = (yrimmig > 2013)))


ag_2013_int_fe <- lm(prop_same_sex_adj ~ distw + contig + comlang_off + comlang_ethno + colony +
                   wage_dif + unemp_dif + polity5  + stock_prop + bpld +
                     post_2013*origin_score,
         data = mutate(acs_prop_yrimmig_policy, post_2013 = (yrimmig > 2013)))


ag_2013_spouse_int <- lm(prop_spouse_same_sex_adj ~ distw + contig + comlang_off + 
                           comlang_ethno + colony + bpld +
                   wage_dif + unemp_dif + polity5  + stock_prop +
                     post_2013*origin_score,
         data = mutate(acs_prop_yrimmig_policy, post_2013 = (yrimmig > 2013)))

se_list <- list()
mod_list <- list(ag, ag_country_orig, ag_country_orig_fe,
                 ag_country_orig_fe_2013, ag_2013_int_fe, ag_2013_spouse_int)
for(mod_num in 1:length(mod_list)){
  se_list[[mod_num]] <- coef(summary(mod_list[[mod_num]], cluster = c("bpld")))[, 2]
}


stargazer(mod_list,
          header = F,
          model.names = F,
          keep = c('origin_score', 'polity5', 'post_2013'),
          order = paste0("^", c('origin_score', 'polity5', 'post_2013TRUE', 
                                'post_2013TRUE:origin_score') , "$"),
          covariate.labels = c('Country LGBT policy score', 'Polity5 democratization',
                                'Post-2013', 'Country score × Post-2013'),
          dep.var.labels   = c("Percent in same-sex couples", "Married"),
          add.lines = list(c('Country controls?', 'no', rep('yes', 5)),
                           c('Country FEs?', 'no', 'no', rep('yes', 4))),
          se = se_list,
          keep.stat = c('n'),
          star.cutoffs = c(0.1, 0.05, 0.01, 0.001),
          star.char = c('†', '*', '**', '***'),
          notes = c("Note: †p<0.1; *p<0.05; **p<0.01; ***p<0.001",
                    "Source: American Community Survey 2008-2019"),
          notes.label = '',
          notes.align = 'l',
          notes.append = F,
          label = 'tab:country-props',
          title = 'ADJUSTED: OLS regressions of percent of immigrants in same-sex couples by year of immigration and country of origin. Country-clustered standard errors shown in parentheses. Country controls include population-weighted distance, contiguous border, common official language, common ethnic language, colonial relationship, wage differential, unemployment differential, proportion same-country stock, and Polity 5 measure of democratization.')


# mod_list <- list(ag, ag_country_orig, ag_country_orig_fe, 
#                  ag_country_orig_fe_2013, ag_2013_int_fe, ag_2013_spouse_int)
# for(mod_num in 1:length(mod_list)){
#   mod_list[[mod_num]] <- coef(summary(mod_list[[mod_num]], cluster = c("bpld")))
# }
# 
# keep_coefs <- c('Country LGBT policy score' = 'origin_score', 
#                 'Polity5 democratization' = 'polity5', 
#                 'Post-2013' = 'post_2013TRUE', 
#                 'Country score × Post-2013' = 'post_2013TRUE:origin_score')
#    
# 
# export_summs(mod_list,
#        coefs = keep_coefs,
#        statistics = c('N' = 'nobs'),
#        stars = c(`†`= 0.1, `*`= 0.05, `**` = 0.01, `***` = 0.001),
#        note = '{stars}. 
#                Source: American Community Survey 2008-2019') %>%
#   set_caption('OLS regressions of percent of immigrants in same-sex couples by year of immigration and country of origin. Country-clustered standard errors shown in parentheses. Country controls include population-weighted distance, contiguous border, common official language, common ethnic language, colonial relationship, wage differential, unemployment differential, proportion same-country stock, and Polity 5 measure of democratization.') %>%
#   add_rows(matrix(c('Country controls?', 'no', rep('yes', 5),
#                 'Country FEs?', 'no', 'no', rep('yes', 4)),
#            byrow = T, nrow = 2) , 
#            after = nrow(.) - 1)

```

# Accounting for mismatch

```{r mismatch}
tibble(`Study Year` = c(2010, 2010, 2016, 2016),
           Relationship = c('Married', 'Unmarried Partner', 'Married', 'Unmarried Partner'),
           `Mail` = c('59%', '7%', '47.4%', '5.6%'), 
           `Internet` = c('NA', 'NA', '22.5%', '2.4%'), 
           `CAPI/CATI` = c('46%', '13%', 'Unknown', 'Unknown'))
```


```{r respmode}
tabyl(acs_couple_policy, respmode, year) %>%
  adorn_percentages('col')
  

tabyl(filter(acs_couple_policy, same_sex == T), respmode, year) %>%
  adorn_percentages('col')
```




# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\noindent


