---
output:
  bookdown::pdf_document2:
  # bookdown::word_document2:
  #   reference_docx: "word-template.docx"
    toc: no
    number_sections: no
    pandoc_args: !expr rmdfiltr::add_wordcount_filter(rmdfiltr::add_citeproc_filter(args = NULL))
    latex_engine: xelatex
    keep_tex: no

header-includes:
  - \usepackage{setspace}\doublespace
  - \usepackage{bbm}
editor_options: 
  
  chunk_output_type: console
citeproc: no
# fontfamily: mathpazo
mainfont: "Times New Roman"
fontsize: 12pt
geometry: margin=1in
indent: yes
link-citations: yes
linkcolor: blue
bibliography: "/Users/nathan/Google Drive/Projects/2020 Same-Sex Immigrant Couples/ssimm/Same-Sex Immigration.bib"

title: "TESS Proposal: Skill, Sexuality, and Immigrant Deservingness"

date: "`r format(Sys.time(), '%B %e, %Y')`"
author:
- Nathan I. Hoffmann, Department of Sociology, University of California, Los Angeles
- Kristopher Velasco, Department of Sociology, Princeton University

---

\newcommand{\tabitem}{~~\llap{\textbullet}~~}

\newpage


**Overview**: Do Americans view lesbian and gay (LG) migrants as more deserving to enter the country than their straight counterparts? This question has yet to be evaluated, but is important to address for two reasons. First, recent changes in federal policy have contributed toward significant increases in LG migrants coming to the U.S. [@hoffmann_2021_making; @vogler_2016]. Despite this growth, how Americans view these types of migrants is unknown. Second, while Americans are increasingly polarized on their views toward migration, support for gay and lesbian migrants may be cross-cutting. There are now strong majorities and bipartisan support for related issues like marriage equality. In foreign policy, even the Trump Administration discursively promoted pro-gay programs -- enhancing the image of the U.S. as a tolerant society amid rising ethnonationalism and xenophobia. Therefore, this project proposes to investigate whether sexual minorities are evaluated as more deserving due to perceived cultural similarity to the U.S. This will help disentangle Americans' preferences for migrants' presumed cultural similarity from economic potential and humanitarian merit as well as delineate public opinion of this under-studied group.


<!-- According to American Community Survey data, numbers of different-sex couples including immigrants increased by 22 percent from 2013 to 2019 (from 7.8 million to 9.5 million), while those of corresponding same-sex couples grew from 44 thousand to 107 thousand in the same period, an increase of 140 percent.  -->


**Background**: Two recent policy changes have contributed to a rapid rise in lesbian and gay immigrants in the United States. In 2011, President Obama moved to make queer refugees a "population of concern" for the U.S. [@vogler_2016], boosting the number of successful claims [@shaw_2021_lgbt]. Then, in 2013, the Defense of Marriage act ended, allowing U.S. citizens to sponsor the visa of a same-sex partner for the first time [@edwards_2013]. Since, numbers of same-sex couples including immigrants increased 140 percent -- dramatically greater compared to the 22 percent increase for their heterosexual counterparts [@hoffmann_2021_making]. While most scholarship on LG immigrants focuses on cases of asylum-seekers fleeing repression [@murray_2014_real; @sam_2015_teacher; @akin_2017_queer; @dhoest_2019_learning; @giametta_2020_new; @saleh_2020_queer], recent work suggests that the typical LG immigrant may be privileged and coming from progressive contexts [@hoffmann_2021_making; @hoffmann_2022_policy]. These observations raise our key research questions: To what extent do Americans leverage sexual orientation as a salient factor to determine the deservingness of potential LG immigrants? Does economic potential or humanitarian merit condition these effects?

Previous experimental work has attempted to assess how native-born respondents assess the "deservingness" of migrants to gain legal entry to their country. This work broadly supports three theories of deservingness: *cultural similarity*, *economic potential*, and *humanitarian merit*.

<!--  Do they see refugees persecuted for their sexuality as more deserving of entry than privileged, high-earning LGB immigrants? When considering who should migrate to the United States, how do Americans evaluate sexuality as compared to earnings potential or credible danger? -->    

We hypothesize that *cultural similarity* will be the primary mechanism through which Americans determine LG immigrant deservingness. The limited, relevant research that exists finds Americans to be biased against Muslims and non-English speakers while Christians and English speakers are viewed as more deserving [@bansak_2016_how; @donnaloja_2022_british]. This work supports "norms-based," "sociotropic" explanations [@hainmueller_2015_hidden]. One such norm in development is that the U.S. is welcoming of lesbian and gay individuals -- at least in international imagery [@snow_2020_routledge]. Many right-wing parties across Western democracies, too, promote gay-friendly foreign images and national identities [@magni_2023_why]. Often, this is done to justify opposition to supposedly homophobic Black, Brown, and Muslim immigrants or to justify foreign interventions like foreign aid conditionalities (e.g., homonationalism) [@puar_2007_terrorist; @kwon_2022_multidimensional]. Thus, just like language or religion signals cultural closeness, so too will an openly gay or lesbian sexual identity.

But theories of *economic potential* have greatest empirical support. Numerous studies find that highly educated migrants working in prestigious, high-earning professions are seen as most deserving of entry [@hainmueller_2010_attitudes; @helbling_2014_why; @hainmueller_2015_hidden; @donnaloja_2022_british]. Although economic potential is not a legal consideration when awarding refugee status, respondents find hypothetical refugees with economic potential to be more deserving [@bansak_2016_how; @lawlor_2021_deservingness]. But LG Americans experience greater rates of poverty and have lower incomes compared to straight Americans [xx]. Despite this, many perceive this population as being wealthy or, at least, having higher discretionary spending [xx]. This may transfer over toward the deservingness of LG migrants if Americans perceive this population has having greater economic potential.

Additionally, work on refugees has pointed to the importance of *humanitarian merit* in matters of deservingness. While @bansak_2016_how find greater support in Europe for immigrants with greater economic potential, they also find that respondents favor immigrants coming for "humanitarian" rather than "economic" reasons. In the Danish context, @hedegaard_2022_attitudes finds that respondents are less likely to support climate migrants than typical refugees, but these two groups are both considered more deserving than economic migrants. As repression against LG communities increases in some countries like Russia [xx], this may prime Americans to be more sympathetic toward LG migrants on humanitarian grounds.

<!--- In Japan, @fraser_2022_role find that immigrants fleeing natural disaster are seen as more deserving than those migrating due to political protest, labor shortage, or civil war.  --->

It is therefore important to disentangle cultural theories of immigrant deservingness from economic or humanitarian explanations. Doing so has yet to be convincingly executed -- neither for LG immigrants, specifically, nor all immigrants, generally. Part of the issue is that many of these aspects of countries and individuals are correlated. Immigrants originating in wealthier countries tend to be considered to have both more economic potential and cultural similarity. Humanitarian migrants usually originate in less wealthy countries that are regarded as having less cultural similarity or economic potential. And besides religion and language, few studies have assessed cultural similarity theory.  

We propose using a conjoint survey experiment to isolate these components of deservingness. Despite the recent rise of LG immigrants in the U.S., sexuality has been under-explored in studies of immigrant deservingness.^[@lawlor_2021_deservingness include persecution due to sexual orientation (along with religion) as a “humanitarian deservingness cues” for hypothetical asylum seeker profiles, but not for refugee profiles, and they do not disaggregate these two cues. @hedegaard_2022_attitudes list "sexuality" as a possible form of persecution for hypothetical refugee profiles, along with race, religion, nationality, or political orientation.] We will use sexual minority status as a measure of cultural similarity that overcomes these issues. Sexual minorities are present throughout the world, avoiding issues of country-level correlates. The present era is characterized by rapidly changing policies and attitudes regarding sexual minorities, as well as substantial global heterogeneity. A large majority of Americans now support same-sex marriage and other rights for same-sex couples [@ofosu_2019_samesex]. The proposed study will be one of the first survey experiments to consider immigrant sexuality explicitly.  

To assess the degree to which sexuality matters as a sign of cultural similarity, we will randomize two other attributes of cultural similarity: language and religion. And while we theorize that the deservingness of this type of immigrant may cut across typical divisions, we still anticipate some heterogeneous effects across respondents. Namely, we hypothesize that respondents with greater cultural affinity with and support for LG communities will also view LG migrants as more deserving as well. We will measure these signals of cultural closeness as: levels of education, sexual/gender minority status, political ideology, and religiosity.

**Research Design**: We will use a conjoint survey experiment, which allows isolation of these components [@hainmueller_2014_causal]. Respondents will read two vignettes describing hypothetical immigrants and choose the one they prefer to gain entry to the United States [@lawlor_2021_deservingness; @fraser_2022_role]. 


For the immigrant profiles, we will vary four attributes. Two are controls: gender has two levels (man and woman) and country GDP has two levels (moderately wealthy and poor). The other attributes test our hypotheses. Skill has three levels (has an MD and works as a cardiologist; has a high school degree and works as a restaurant manager; and has a primary school education and works as a cleaner). Language has two levels (speaks English and does not speak English), religion has two levels (Christian and Muslim), and sexuality has two levels (gay/lesbian and straight). Finally, reason for migration has two levels (could not find work due to high unemployment; feared government persecution). In all, this creates 192 potential profiles for respondents to evaluate.  


We will present respondents with two vignettes. They will then indicate which one they see as more deserving of being admitted to the United States. One example profile might read: "Immigrant 1 wishes to be admitted as an immigrant to the United States. She comes from a moderately wealthy country, has a primary school education, and works as a cleaner. She does not speak English, is Christian, and identifies as lesbian. She had to leave her country because she could not find work due to high unemployment."  

After choosing which profile they wish to see admitted to the U.S., respondents will give a rating between 1 and 7 of each profile's deservingness and a rating of perceived sharing of American values. Further details about the survey instrument are in the Appendix.  

In addition to estimating average marginal component effects (AMCEs) for the attributes of interest [@hainmueller_2014_causal], we will test for the presence of heterogeneous effects for subsamples of respondents [@leeper_2020_measuring], including by political ideology, educational level, sexual/gender identity, and religiosity.   

We are requesting a U.S. citizen subsample and the LGBT question from the Core Adult Profile. Each respondent will be shown the survey instrument twice, for a total of ten questions plus two sets of vignettes. With these 12 items and the subsample request, we anticipate a sample size of 1,710 evaluating 3,420 sets of profiles, which our power analysis suggests is sufficient to detect our effects of interest.  

**Pretest Results**: Our pilot study...  

**Contribution**: This study contributes to literature on immigrant deservingness and sexual minorities. Despite the rapid rise of LG immigrants in the U.S., we know little about how the American public views these immigrants. Furthermore, previous studies of immigrant deservingness have rarely considered how cultural similarity might shape respondents' choices. This research will clarify this area for scholars of immigration and sexual minorities, inform policymakers of public opinion, and provide activists for immigrant and queer rights with tools to shape their advocacy work.

\newpage

\singlespacing

# References

<div id="refs"></div>

\newpage


# Appendix

## Survey Instrument

\setlength\parindent{0pt}

Include panel question on LGBT identity. Each respondent will be shown two sets of profiles. For each set, they will be asked the following five questions:

\vspace{1cm}

*1. Please carefully read the following two descriptions of potential immigrants to the United States. Then indicate which one you personally would prefer to see admitted to the United States.*  


> Immigrant [1/2] wishes to be admitted as an immigrant to the U.S. [He/she] comes from a [GDP] country, [Skill]. [He/she] [Language], is [Religion], and identifies as [Sexuality]. [He/she] had to leave [his/her] country because [he/she] [reason].  


Randomize:  
\begin{tabular}{p{0.3\linewidth}  p{0.5\linewidth}}
\hline
\bf{Attribute} & \bf{Vignette text} \\
\hline
Gender & \tabitem man \\
& \tabitem woman \\
 \\
Country GDP
& \tabitem moderately wealthy \\
& \tabitem low-income \\

 \\
Skill
& \tabitem has an MD and works as a cardiologist \\
& \tabitem has a high school degree and works as a restaurant manager \\
& \tabitem has a primary school education and works as a cleaner \\

 \\
Language
& \tabitem speaks English \\
& \tabitem does not speak English \\
 \\
Religion
& \tabitem Christian \\
& \tabitem Muslim \\

 \\
Sexuality
& \tabitem gay/lesbian \\
& \tabitem straight (that is, not gay/lesbian) \\
 \\
Reason for migration
& \tabitem feared government persecution \\
& \tabitem could not find work due to high unemployment \\
\hline
\end{tabular}

\newpage 

Example:  
\begin{tabular}{p{0.45\linewidth}  p{0.45\linewidth}}
\hline
\bf{Immigrant 1} & \bf{Immigrant 2} \\
\hline
Immigrant 1 is a woman from a moderately wealthy country. She has a primary school education and works as a teacher. She speaks English, is Muslim, and identifies as lesbian. She had to leave her country because she could not find work.
& Immigrant 2 is a man from a low-income country. He has an MD and works as a cardiologist. He does not speak English, is Christian, and identifies as straight (that is, not gay). He has to leave his country because he feared government persecution. \\
 \hline
\end{tabular}  

\vspace{1cm}  

Based on their descriptions, which of these two immigrants would you personally would prefer to see admitted to the United States?  

- Immigrant 1
- Immigrant 2
  
The following two questions are about **immigrant 1**:  

2. *On a scale from 1 to 7, where 1 signifies that the U.S. should absolutely not admit immigrant 1 and 7 signifies that the U.S. should definitely admit this immigrant, how would you rate immigrant 1?*  

3. *On a scale from 1 to 7, where 1 signifies having no shared values and 7 signifies a great deal of shared values, to what degree do you think immigrant 1 has shared values with the U.S.?*  


The following two questions are about **immigrant 2**:  

4. *On a scale from 1 to 7, where 1 signifies that the U.S. should absolutely not admit immigrant 1 and 7 signifies that the U.S. should definitely admit this immigrant, how would you rate immigrant 1?*  

5. *On a scale from 1 to 7, where 1 signifies having no shared values and 7 signifies a great deal of shared values, to what degree do you think immigrant 1 has shared values with the U.S.?*




## Power analysis





