---
output:
  bookdown::pdf_document2:
  # bookdown::word_document2:
  #   reference_docx: "word-template.docx"
    toc: no
    number_sections: no
    pandoc_args: !expr rmdfiltr::add_wordcount_filter(rmdfiltr::add_citeproc_filter(args = NULL))
    latex_engine: xelatex
    keep_tex: no

header-includes:
  # - \usepackage{setspace}\doublespace
  - \usepackage{bbm}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  # - \setlength{\headheight}{15pt}
  - \lhead{\textit{Pregistration}}
  - \rhead{\textit{Sexuality, Cultural Similarity, and Immigrant Deservingness}}
editor_options: 
  
  chunk_output_type: console
citeproc: no
# fontfamily: mathpazo
# mainfont: "Times New Roman"
# fontsize: 12pt
geometry: margin=1in
indent: yes
link-citations: yes
linkcolor: blue
bibliography: "/Users/nathan/My Drive/Projects/2020 Same-Sex Immigrant Couples/ssimm/Same-Sex Immigration.bib"
#csl: chicago-author-date.csl

title: "Sexuality, Cultural Similarity, and Immigrant Deservingness"
subtitle: "Analysis"


# date: "`r format(Sys.time(), '%B %e, %Y')`"
# author:
# - Nathan I. Hoffmann, Department of Sociology, University of California, Los Angeles
# - Kristopher Velasco, Department of Sociology, Princeton University

---

\newcommand{\tabitem}{~~\llap{\textbullet}~~}


```{r setup, include = F}
knitr::opts_chunk$set(echo = F, warning = F, message = F, cache = T, 
                      dpi = 300)
library(here)
library(huxtable)
library(haven)
library(patchwork)
library(cregg)
library(rdss)
library(DeclareDesign)
library(tidyverse)

options("yaml.eval.expr" = TRUE)

theme_set(theme_classic(base_family = 'Palatino') + 
            theme(legend.title=element_blank(),
                  panel.grid.major.y = element_line('grey80'),
                  legend.background = element_rect(fill = "transparent")))
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Dark2") +
  scale_fill_brewer(palette="Dark2")
```


```{r load}
prolific <- read_csv(here('survey', 'prolific.csv')) %>%
  filter(Status == 'APPROVED' | Status == 'AWAITING REVIEW')
col_names <- names(read_csv(here('survey', 'survey.csv'), n_max = 0))
survey_raw <- read_csv(here('survey', 'survey.csv'), col_names = col_names, skip = 3) %>%
  filter(PROLIFIC_PID %in% prolific$`Participant id`,
         PROLIFIC_PID != '644af405d31dd25adf037157', # failed attention check
         PROLIFIC_PID != '6048622d518a190008dfbe38', # extra person
         Finished == T)
# 
# not_approved <- prolific %>%
#   filter(Status != 'APPROVED') %>%
#   pull(`Participant id`)
# filter(survey_raw, PROLIFIC_PID %in% not_approved) %>%
#   select(Finished, PROLIFIC_PID)
# 
# prolific %>%
#   filter(!(`Participant id` %in% survey_raw$prolific_pid)) %>%
#   arrange(`Participant id`) %>%
#   select(`Participant id`, Status)
# 
# unfinished_maybe <- survey_raw %>%
#   filter(Finished != T) %>%
#   pull(PROLIFIC_PID)
# finished_ids <- survey_raw %>%
#   filter(Finished == T) %>%
#   pull(PROLIFIC_PID)
# unfinished <- unfinished_maybe[!(unfinished_maybe %in% finished_ids)]
# 
# survey_raw %>%
#   filter(PROLIFIC_PID %in% unfinished) %>%
#   View()
# 
# survey_raw %>%
#   filter(Finished != T) %>%
#   View()
# 
# survey_raw %>%
#   filter(PROLIFIC_PID %in% unfinished)
# 
# survey_raw %>%
#   filter(PROLIFIC_PID == '6111811553d54da81ce61f21') %>% View()
# 
# survey_raw %>%
#   filter(PROLIFIC_PID %in% unfinished) %>%
#   arrange(PROLIFIC_PID) %>%
#   select(PROLIFIC_PID, Finished)
#   group_by(PROLIFIC_PID) %>% count()
#   select(PROLIFIC_PID, everything()) %>% View()
# 
# survey_raw %>%
#   filter(!(PROLIFIC_PID %in% prolific$`Participant id`)) %>%
#   select(PROLIFIC_PID)
# 
# survey_raw %>%
#   arrange(PROLIFIC_PID) %>%
#   group_by(PROLIFIC_PID) %>%
#   filter(n()>1) %>% 
#   select(PROLIFIC_PID, everything()) %>%
#   View()
# 
# 
# prolific %>%
#   filter(!(`Participant id` %in% survey_raw$PROLIFIC_PID)) %>%
#   select(`Participant id`)
# 
# survey_raw %>% filter(PROLIFIC_PID %in% 
#                         c('5a91877e777df200015fa0f5',
#                           '608a58c50e40c85b2f5f94ec',
#                           '6111811553d54da81ce61f21',
#                           '60fd957e79d70d6be755ad8c')) %>% View()


# Attention check
  # survey_raw %>%
  #   filter(!str_detect(tolower(attention_color_5_TEXT), 'green') |
  #            !(str_detect(as.character(attention_number_6_TEXT), '9') |
  #               str_detect(tolower(as.character(attention_number_6_TEXT)), 'nine'))
  #          ) %>%
  #   mutate(minutes = `Duration (in seconds)`/60) %>%
  #   select(prolific_pid, attention_color_5_TEXT, attention_number_6_TEXT, minutes)



survey <- survey_raw %>%
  #mutate(choice1 = Q3, choice2 = Q3, choice3 = Q13, choice4 = Q13) %>%
  pivot_longer(c(gender1:reason4, rating1:value2, rating3:value4), 
               names_to = c('.value', 'number'), names_pattern = ('(.*)(\\d+)')) %>%
  filter(!is.na(gender)) %>%
  mutate(chosen = case_when(
    choice_a == 'Immigrant 1 should be admitted.' & number == 1 ~ 1,
    choice_a == 'Immigrant 2 should be admitted.' & number == 2 ~ 1,
    choice_b == 'Immigrant 3 should be admitted.' & number == 3 ~ 1,
    choice_b == 'Immigrant 4 should be admitted.' & number == 4 ~ 1,
    choice_c == 'Immigrant 1 should be admitted.' & number == 5 ~ 1,
    choice_c == 'Immigrant 2 should be admitted.' & number == 6 ~ 1,
    choice_d == 'Immigrant 3 should be admitted.' & number == 7 ~ 1,
    choice_d == 'Immigrant 4 should be admitted.' & number == 8 ~ 1,
    T ~ 0),
    sexuality = factor(ifelse(sexuality %in% c('lesbian', 'gay'), 'lesbian or gay', 'straight'), 
                       levels = c('straight', 'lesbian or gay')),
    across(c(gender, sexuality, gdp, skill, lang, religion, reason), function(x) factor(x)),
    across(c(rating, value), function(x) as.numeric(substr(x, 1,1)))) %>%
  mutate(skill = recode(skill, 
                        'has a high school degree, and works as a restaurant manager' = 
                          'high school',
                        'has a primary school education, and works as a cleaner' = 
                          'primary school',
                        'has an MD, and works as a cardiologist' = 'MD'),
         reason = recode(reason, 'could not find work due to high unemployment' = 
                           'could not find work'),
         resp_religion = factor(case_when(
           resp_religion %in% c('Other Christian', '
                                Protestant (Baptist, Methodist, Non-denominational, Lutheran, Presbyterian, Pentecostal, Episcopalian, Reformed, Church of Christ, Jehovah’s Witness, etc.)',
                                'Roman Catholic (Catholic)') ~ 'Christian',
           resp_religion %in% c('Agnostic (not sure if there is a God)',
                                'Atheist (do not believe in God)',
                                'Nothing in particular') ~ 'Atheist/not religious',
           T ~ 'Other')),
         resp_politics = factor(ifelse(
             resp_politics %in% c('Independent', 'None of these'), 'other',
             resp_politics)),
         resp_sexuality = factor(case_when(
           resp_sexuality %in% c("I don't know the answer", 'Something else') ~ 'Other',
           resp_sexuality %in% c('Bisexual', 'Lesbian or gay') ~ 'Lesbian/gay/bisexual',
           resp_sexuality == 'Straight (that is, not gay or lesbian)' ~ 'Straight'
         )),
         resp_education = factor(resp_education),
         resp_pro_econ = resp_imm_support_1,
         resp_pro_job = resp_imm_support_2,
         resp_pro_tax = resp_imm_support_3,
         resp_pro_culture = resp_imm_support_4,
         resp_pro_help = resp_imm_support_5,
         resp_con_econ = resp_imm_support_6,
         resp_con_job = resp_imm_support_7,
         resp_con_welfare = resp_imm_support_8,
         resp_con_crime = resp_imm_support_9,
         resp_con_pop = resp_imm_support_10,
         resp_con_culture = resp_imm_support_11
  )


# survey <- survey %>% slice(rep(row_number(), each = 10)) %>%
#   mutate(prolific_pid = 1:n())

```


```{r general, fig.height = 3, fig.cap = 'Estimated marginal means and AMCEs for Prolific Academic survey study of 100 respondents each shown 2 sets of profiles. Standard errors are clustered within respondent.'}
(plot(mm(survey, chosen ~  sexuality, 
        id = ~prolific_pid)) + geom_vline(xintercept = 0.5, size = .2)) +
  plot(cj(survey, chosen ~  sexuality, 
        id = ~prolific_pid)) &
  theme()



```

```{r interaction, fig.height = 3, fig.cap = 'Marginal means of the interaction between sexuality and the reason for migration'}
int_cj <- cj(survey, chosen ~ sexuality, id = ~prolific_pid, estimate = 'mm', 
             by = ~reason)
int_cj_dif <- cj(survey, chosen ~ sexuality, id = ~prolific_pid, estimate = 'mm_diff', 
                 by = ~reason)
rbind(int_cj, int_cj_dif) %>%
  mutate(BY = recode(BY, 'could not find work' = 'work',
                     'feared government persecution' = 'persecution',
                     'feared government persecution - could not find work' = 
                       'persecution - work')) %>%
  plot() + 
  ggplot2::facet_wrap(~BY, ncol = 3) +
  # geom_vline(xintercept = 0.5, size = .2)
  geom_vline(aes(xintercept = ifelse(statistic == 'mm', 0.5, 0)), size = .2)
```

\newpage

```{r subgroups, fig.height = 7, fig.cap = 'Marginal means for subgroups'}
survey <- survey %>%
  mutate(BA = factor(case_when(
    resp_education == "Bachelor's degree or higher" ~ 'BA',
    resp_education != "Bachelor's degree or higher" ~ 'no BA')),
    resp_overpop = factor(case_when(
      resp_con_pop %in% c('Agree', 'Somewhat agree') ~ 'Agree',
      resp_con_pop %in% c('Disagree', 'Somewhat disagree') ~ 'Disgree',
    ))
    )

(plot(cj(survey, chosen ~ sexuality, estimate = 'mm',
        id = ~prolific_pid, by = ~ resp_education),
        group = 'resp_education') +
  geom_vline(xintercept = .5, size = .2) +
  theme(legend.position = 'right')) /
(plot(cj(survey, chosen ~ sexuality, estimate = 'mm',
        id = ~prolific_pid, by = ~ resp_politics),
        group = 'resp_politics') +
  geom_vline(xintercept = .5, size = .2) +
  theme(legend.position = 'right')) /
(plot(cj(survey, chosen ~ sexuality, estimate = 'mm',
        id = ~prolific_pid, by = ~resp_religion),
        group = 'resp_religion') +
  geom_vline(xintercept = .5, size = .2) +
  theme(legend.position = 'right')) /
(plot(cj(survey, chosen ~ sexuality, estimate = 'mm',
        id = ~prolific_pid, by = ~ resp_sexuality),
        group = 'resp_sexuality') +
  geom_vline(xintercept = .5, size = .2) +
  theme(legend.position = 'right')) 
```


```{r int-overpop, fig.cap = 'Do you agree with the following statement: "Immigration contributes to overpoulation."'}
(plot(cj(survey, 
         chosen ~ sexuality, estimate = 'mm',
        id = ~prolific_pid, by = ~ resp_overpop),
        group = 'resp_overpop') +
  geom_vline(xintercept = .5, size = .2) +
    ggtitle('Full sample')) +
(plot(cj(filter(survey, resp_politics == 'Democrat'), 
         chosen ~ sexuality, estimate = 'mm',
        id = ~prolific_pid, by = ~ resp_overpop),
        group = 'resp_overpop') +
  geom_vline(xintercept = .5, size = .2) +
    ggtitle('Democrat')) +
  (plot(cj(filter(survey, resp_politics == 'Republican'), 
         chosen ~ sexuality, estimate = 'mm',
        id = ~prolific_pid, by = ~ resp_overpop),
        group = 'resp_overpop') +
  geom_vline(xintercept = .5, size = .2) +
   ggtitle('Republican')) + 
  theme(legend.position = 'bottom')

```

