---
output:
  # bookdown::pdf_document2:
  bookdown::word_document2:
    reference_docx: "word-template.docx"
    toc: no
    number_sections: yes
    pandoc_args: !expr rmdfiltr::add_wordcount_filter(rmdfiltr::add_citeproc_filter(args = NULL))
    latex_engine: xelatex
always_allow_html: true
header-includes:
  # - \usepackage{setspace}\doublespace
  - \setlength{\headheight}{13.6pt}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \lhead{Nathan I. Hoffmann}
  - \rhead{`r format(Sys.time(), '%B %e, %Y')`}
editor_options: 
  chunk_output_type: console
citeproc: no
fontfamily: mathpazo
fontsize: 11pt
geometry: margin= 1in
indent: yes
link-citations: yes
linkcolor: blue
lang: 'en-US'
# bibliography: "/Users/nathan/My Drive/Projects/2020 Same-Sex Immigrant Couples/Same-Sex Immigration.bib"
title: "Appendix"
subtitle: "The Geography of Immigrants in Same-Sex Couples in the United States"
# date: "September 1, 2024"
# date: "`r format(Sys.time(), '%B %e, %Y')`"
author:
- Nathan I. Hoffmann, Department of Sociology, UCLA
- Kristopher Velasco, Department of Sociology, Princeton University
---

<!-- Turn off hyphenation -->

<!-- \usepackage[none]{hyphenat} -->

```{r setup, include=F}
library(knitr)
library(broom)
library(huxtable)
library(sandwich)
library(lmtest)
library(here)
library(stargazer)
library(patchwork)
library(flextable)
library(kableExtra)
library(maps)
library(tigris)
library(fiftystater)
library(ggthemes)
library(srvyr)
library(tidyverse)


knitr::opts_chunk$set(echo = F, warning = F, message = F, cache = T, # results = 'asis',
                      cache.lazy = F, dpi = 1200)


options("yaml.eval.expr" = TRUE)

uclablue = '#2774AE'
gray = '#808080'
black = '#000000'
uclagold = '#FFB81C'
rust = '#C47A2B'
# ucla_palette = c(uclablue, black, gray)
ucla_palette = c(black, uclablue, rust)
palette_dark <- rev(RColorBrewer::brewer.pal(n=3,"Dark2"))

# theme_set(theme_cowplot(font_family = 'Palatino') + 
theme_set(theme_classic() + 
            theme(legend.title=element_blank(), 
                  axis.line = element_line(size = .3), 
                  axis.ticks = element_line(size = .3),
                  panel.grid.major.y = element_line('grey80', size = .3),
                  legend.background = element_rect(fill = "transparent")))
ggplot <- function(...) ggplot2::ggplot(...) + scale_color_manual(values = ucla_palette) +
  scale_fill_manual(values = ucla_palette)

# theme_set(theme_classic() + 
#             theme(axis.line = element_line(size = .3), 
#                   axis.ticks = element_line(size = .3), 
#                   legend.title=element_blank(), 
#                   panel.grid.major.y = element_line('grey80', size = .3),
#                   legend.background = element_rect(fill = "transparent")))
# ggplot <- function(...) ggplot2::ggplot(...) + scale_color_brewer(palette="Dark2") +
#   scale_fill_brewer(palette="Dark2")

# library(colorspace)
# colorspace_palette = 'RdPu'
# ggplot <- function(...) ggplot2::ggplot(...) +
#   scale_color_discrete_sequential(palette=colorspace_palette) +
#   scale_fill_discrete_sequential(palette=colorspace_palette)

options(scipen=1, digits=2)
knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",")
})
knitr::opts_chunk$set(error=TRUE) 

set_flextable_defaults(font.family = 'Times New Roman',
                       # padding.bottom = 1,
                       # padding.top = 1,
                       # padding.left = 3,
                       # padding.right = 1,
                       theme_fun = 'theme_booktabs',
                       digits = 3, 
                       big.mark = ',',
                       line_spacing = 1)

```

```{r load, include = F}
# acs_ind <- readRDS(here('data', 'acs_ind.rds')) 


# acs_count_base <- read_csv(here('data', 'acs_count_base.csv')) 

all_geo <- read_csv(here('data', 'immigrants_geo.csv')) %>% 
  mutate(group = case_when(
    imm_couple == 'none' ~ 'Same-sex, non-immigrant',
    imm_couple != 'none' & same_sex == T ~ 'Same-sex, immigrant',
    imm_couple != 'none' & same_sex == F ~ 'Different-sex, immigrant'
  )) %>%
  mutate(children = ifelse(nchild > 0, 'has children', 'no children'),
         ethnicity = case_when(
           hispan != 'not hispanic' ~ 'Hispanic',
           race == 'white' ~ 'White',
           race %in% c("other asian or pacific islander", "chinese", "japanese") ~ "Asian",
           race == 'black/african american' ~ 'Black',
           !is.na(race) ~ 'Multiracial or Other'),
         lgbt_nonprofits = ifelse(year >= 2022, NA, lgbt_nonprofits),
         immigrant_nonprofits = ifelse(year >= 2022, NA, immigrant_nonprofits),
         married = ifelse(year < 2012 & same_sex == T,
                                 NA, married))

all_geo_survey <- all_geo %>% 
  as_survey_design(weights = perwt)

immigrants <- all_geo %>%
  filter(imm_couple != 'none') 

immigrants_survey <- immigrants %>% 
  as_survey_design(weights = perwt)

acs_geo <- read_csv(here('data', 'acs_geo_survey.csv')) 



  # left_join(select(read_csv(here('geo/files', 'nonprofits_puma.csv')), -statefp), by = c()) %>%
  # mutate(lgbt_nonprofits = ifelse(is.na(lgbt_nonprofits), 0, lgbt_nonprofits)) %>%
  # left_join(select(read_csv(here('geo/files', 'imm_nonprofits.csv')), -statefp)) %>%
  # mutate(immigrant_nonprofits = ifelse(is.na(immigrant_nonprofits), 0, immigrant_nonprofits))

# acs_geo <- read_csv(here('data', 'acs_geo_survey.csv')) %>%
#   mutate(across(c(bachelors_puma, black_puma, hispanic_puma, owned_puma, immigrant_puma, poverty_100_puma,
#                   poverty_200_puma, unemployed_puma), 
#                 ~.x*100))

prop_tab <- acs_geo %>%
  select(state, puma) %>%
  distinct() %>%
  left_join(immigrants %>%
    mutate(same_sex = ifelse(same_sex == T, 'same_sex', 'dif_sex')) %>%
    # filter(year == 2019) %>%
    group_by(state, puma, same_sex) %>%
    summarize(n = sum(perwt)) %>%
    ungroup() %>%
    pivot_wider(names_from = 'same_sex', values_from = 'n')) %>% 
  replace(is.na(.), 0) %>%
  # complete(year, state, puma, same_sex, fill = list('n' = 0)) %>%
  mutate(prop = same_sex/(same_sex + dif_sex)*100) %>%
  filter(!is.nan(prop))


prop_tab_year <- acs_geo %>%
  select(state, puma, year) %>%
  left_join(immigrants %>%
    mutate(same_sex = ifelse(same_sex == T, 'same_sex', 'dif_sex')) %>%
    # filter(year == 2019) %>%
    group_by(year, state, puma, same_sex) %>%
    summarize(n = sum(perwt)) %>%
    ungroup() %>%
    pivot_wider(names_from = 'same_sex', values_from = 'n')) %>% 
  replace(is.na(.), 0) %>%
  # complete(year, state, puma, same_sex, fill = list('n' = 0)) %>%
  mutate(prop = same_sex/(same_sex + dif_sex)*100) %>%
  filter(!is.nan(prop)) %>%
  select(state, puma, year, prop) %>%
  left_join(acs_geo) 


gay_prop_tab_year <- acs_geo %>%
  select(state, puma, year) %>%
  left_join(all_geo %>%
    filter(group != 'Different-sex, immigrant') %>%
    # filter(year == 2019) %>%
    group_by(year, state, puma, group) %>%
    summarize(n = sum(perwt)) %>%
    ungroup() %>%
    pivot_wider(names_from = 'group', values_from = 'n')) %>% 
  replace(is.na(.), 0) %>%
  # complete(year, state, puma, same_sex, fill = list('n' = 0)) %>%
  mutate(prop = `Same-sex, immigrant`/(`Same-sex, immigrant` + `Same-sex, non-immigrant`)*100) %>%
  filter(!is.nan(prop)) %>%
  select(state, puma, year, prop) %>%
  left_join(acs_geo) 

  # left_join(immigrants %>% group_by(year, state, puma) %>%
  # summarize(across(c(density, state_policy, lgbt_nonprofits, immigrant_nonprofits), ~mean(.x, na.rm = T))))


count_tab_year <- bind_rows(
  select(acs_geo, state, puma, year) %>% mutate(group = 'Different-sex, immigrant'),
  select(acs_geo, state, puma, year) %>% mutate(group = 'Same-sex, immigrant'),
  select(acs_geo, state, puma, year) %>% mutate(group = 'Same-sex, non-immigrant')) %>%
  left_join(all_geo %>%
    # filter(year == 2019) %>%
    group_by(year, state, puma, group) %>%
    summarize(n = sum(perwt)) %>%
    ungroup()) %>% 
    replace(is.na(.), 0) %>%
  # complete(year, state, puma, same_sex, fill = list('n' = 0)) %>%
  left_join(acs_geo) 
  
  
variable_names <- c('Bachelor\'s degree (%)' = 'bachelors_puma', 
                    'Black (%)' = 'black_puma',
                    'Hispanic (%)' = 'hispanic_puma', 
                    'Annual personal income (thousands of 2023 USD)' = 'inctot_puma',
                    # 'Log mean personal income' = 'log_inctot_puma', 
                    'Individuals own home (%)' = 'owned_puma', 
                    'Mean age' = 'age_puma', 
                    'Immigrant (%)' = 'immigrant_puma',
                    'Individuals under 100% of poverty line (%)' = 'poverty_100_puma', 
                    'Individuals under 200% of poverty line (%)' = 'poverty_200_puma', 
                    'Mean HWSEI occupation score' = 'hwsei_puma', 
                    'Unemployed (%)' = 'unemployed_puma', 
                    'Mean individual\'s value of home ($1000s)' = 'valueh_puma',
                    'Mean individual\'s rent' = 'rent_puma', 
                    'Mean cost of electricity' = 'costelec_puma', 
                    'Density (persons per sq. mile)' = 'density', 
                    'State LGB policy score' = 'state_policy', 
                    'Mean number of LGBT nonprofits' = 'lgbt_nonprofits',
                    'Mean number of immigrant nonprofits' = 'immigrant_nonprofits',
                    'Annual Gross Income (Thousands)' = 'inctot',
                    'Hauser and Warren Socioeconomic Index' = 'hwsei',
                    'High school graduate' = 'hs',
                    'Four-year college graduate' = 'college',
                    'Number of children' = 'nchild',
                    'Has children' = 'has_children',
                    'Married' = 'married',
                    'White' = 'white',
                    'Black' = 'black',
                    'Asian' = 'asian',
                    'Hispanic' = 'hispanic',
                    'Multiracial or Other' = 'other',
                    'Male' = 'male',
                    'Female' = 'female',
                    'Age' = 'age',
                    'n' = 'n',
                    'n (weighted)' = 'n_weighted')


variable_names_swap <- names(variable_names)
names(variable_names_swap) <- as.vector(variable_names)


sample_size <- all_geo %>%
  group_by(group) %>%
  summarize(n = n(),
            n_weighted = sum(perwt))
```


<!-- # (APPENDIX) {-} -->

\setcounter{figure}{0}                      
\renewcommand\thefigure{A.\arabic{figure}} 


\newpage

# Maps of state-level proportions for subgroups



```{r subgroups-calc, eval = F}

# immigrants <- immigrants %>%
#   mutate(married = ifelse(married == T, 'married', 'not married'))

subgroups <- function(variable){
  subgroups_out <- list()
  variable_values <- unique(immigrants[[variable]])
  variable_values <- variable_values[!is.na(variable_values)]
  
  for(value in variable_values){
    subgroups_out[[as.character(value)]] <- immigrants %>%
      mutate(state = tolower(state),
             value_true = !!sym(variable) == value) %>%
      filter(state != 'district of columbia') %>%
      filter(same_sex == T) %>%
      group_by(state) %>%
      summarize(prop = 100 * weighted.mean(value_true, perwt, na.rm = T)) %>% 
      complete() %>%
      replace(is.na(.), 0) %>%
      mutate(variable = variable, value = value)
  }
  
  return(bind_rows(subgroups_out))
}

all_subgroups_list <- list()
for(variable_name in c('sex', 'ethnicity', 'children', 'married')){
  all_subgroups_list[[variable_name]] <- subgroups(variable_name)
}

all_subgroups_list$married <- all_subgroups_list$married %>%
  mutate(value = ifelse(value == T, 'married', 'not married'))

bind_rows(all_subgroups_list) %>%
  write_csv(here('geo/files', 'state_tab_subgroups.csv'))
```

```{r subgroups-map, fig.height = 5.5, fig.cap = 'Percentage of migrants in same-sex couples in each state consisting of particular subgroups, from ACS estimates that incorporate sampling weights (2008-2019 and 2021-2023).'}
state_tab_subgroups <- read_csv(here('geo/files', 'state_tab_subgroups.csv'))

state_tab_subgroups %>%
  mutate(variable = paste0(str_to_title(variable), ':'),
         value = str_to_sentence(value)) %>%
  ggplot(aes(map_id = state, fill = prop)) +
  geom_map(map = fiftystater::fifty_states) +
  expand_limits(x = fiftystater::fifty_states$long, y = fiftystater::fifty_states$lat) +
  coord_map() +
  scale_fill_gradient(low = uclablue, high = uclagold, na.value = 'gray95') +
  theme_void() +
  facet_wrap(~variable + value, ncol = 3) +
  labs(fill = "Subgroup (%)") +
  theme(legend.title = element_text(size=8), legend.text=element_text(size=8)) 

  
```

<!-- \newpage -->

<!-- # Segregation Index for Subgroups -->
<!-- ```{r segregation, fig.cap = 'Stratified by Index of Dissimilarity (H) measures by PUMA for 2008 to 2023, comparing immigrants in same-sex couples to immigrants in different-sex couples or to non-immigrants in same-sex couples.'} -->
<!-- all_geo <- all_geo %>% -->
<!--   mutate(year_group = floor(year/5)*5)  -->

<!-- all_subgroups_list <- list() -->
<!-- for(variable_name in c('sex', 'ethnicity', 'children')){ -->
<!--   variable_values <- unique(immigrants[[variable_name]]) -->
<!--   variable_values <- variable_values[!is.na(variable_values)] -->

<!--   for(variable_value in variable_values){ -->
<!--     all_subgroups_list[[paste0(variable_name, variable_value, 'imm')]] <- all_geo %>% -->
<!--       filter(group %in% c('Same-sex, immigrant', 'Different-sex, immigrant'), -->
<!--              !!sym(variable_name) == variable_value) %>% -->
<!--       group_by(year_group) %>% -->
<!--       group_modify(~segregation::dissimilarity(data = .x,  -->
<!--                                               group = 'group',  -->
<!--                                               unit = c('puma', 'state'), -->
<!--                                               weight = 'perwt') -->
<!--                    ) %>% -->
<!--       mutate(comparison = 'Same-sex, imm. vs. dif.-sex, imm.', -->
<!--              variable = variable_name, -->
<!--              value = variable_value) -->

<!--      all_subgroups_list[[paste0(variable_name, variable_value, 'lgbq')]] <- all_geo %>% -->
<!--       filter(group %in% c('Same-sex, immigrant', 'Different-sex, immigrant'), -->
<!--              !!sym(variable_name) == variable_value) %>% -->
<!--       group_by(year_group) %>% -->
<!--       group_modify(~segregation::dissimilarity(data = .x,  -->
<!--                                               group = 'group',  -->
<!--                                               unit = c('puma', 'state'), -->
<!--                                               weight = 'perwt') -->
<!--                    ) %>% -->
<!--       mutate(comparison = 'Same-sex, imm. vs. same-sex, non-imm.', -->
<!--              variable = variable_name, -->
<!--              value = variable_value) -->
<!--   } -->
<!-- } -->



<!-- bind_rows(all_subgroups_list) %>% -->
<!--   ggplot(aes(x = year_group, y = est, color = comparison, linetype = comparison)) + -->
<!--   geom_line() + -->
<!--   geom_hline(yintercept = 0) + -->
<!--   facet_wrap(~variable + value) + -->
<!--   theme(legend.position = 'bottom') -->


<!-- # bind_rows(yearly_theil, seg_imm, seg_lgbq) %>% -->
<!-- #   ggplot(aes(x = year, y = est, color = comparison, linetype = comparison)) + -->
<!-- #   geom_line() + -->
<!-- #   geom_hline(yintercept = 0) + -->
<!-- #   facet_wrap(~index, scales = 'free') -->
<!-- ``` -->


\newpage

# Characteristics of married people (beginning in 2012)


```{r desc-calc-married, eval = F}
desc_tab <- all_geo_survey %>%
  filter(married == T & year >= 2012) %>%
  group_by(group) %>%
  summarize(across(c(bachelors_puma, black_puma, hispanic_puma, inctot_puma,
                     owned_puma, age_puma, immigrant_puma,
                     poverty_100_puma, poverty_200_puma, hwsei_puma, 
                     unemployed_puma, valueh_puma,
                     rent_puma, costelec_puma, density, state_policy, 
                     lgbt_nonprofits, immigrant_nonprofits), 
            ~ survey_mean(.x, na.rm = T)))

write_csv(desc_tab, here('geo/files', 'desc_tab_married.csv'))

desc_tab_ind <- all_geo_survey %>%
  filter(married == T & year >= 2012) %>%
  mutate(hs = if_else(educ %in% c('HS', 'some col', 'college'), 1, 0),
         college = if_else(educ == 'college', 1, 0),
         has_children = nchild > 0,
         white = ethnicity == 'White',
         black = ethnicity == 'Black',
         hispanic = ethnicity == 'Hispanic',
         asian = ethnicity == 'Asian',
         other = ethnicity == 'Multiracial or Other',
         Female = sex == 'female',
         Male = sex == 'male') %>% 
  group_by(group) %>%
  summarize(across(c(inctot, hs, college, hwsei, has_children, nchild, age,
                     white, black, hispanic, asian, other, Female, Male), 
            ~ survey_mean(.x, na.rm = T)))

write_csv(desc_tab_ind, here('geo/files', 'desc_tab_ind_married.csv'))

# desc_tab_time <- all_geo_survey %>%
#   filter(married == T & year >= 2012) %>%
#   group_by(group, year) %>%
#   summarize(across(c(bachelors_puma, black_puma, hispanic_puma, inctot_puma,
#                      owned_puma, age_puma, immigrant_puma,
#                      poverty_100_puma, poverty_200_puma, hwsei_puma,
#                      unemployed_puma, valueh_puma,
#                      rent_puma, costelec_puma, density, state_policy,
#                      lgbt_nonprofits, immigrant_nonprofits),
#             ~ survey_mean(.x, na.rm = T))) %>%
#   replace(. == 0, NA)
# 
# write_csv(desc_tab_time, here('geo/files', 'desc_tab_time_married.csv'))
```

```{r desc-ind-married}

# desc_tab_se <- immigrants_survey %>%
#   group_by(same_sex) %>%
#   summarize(across(c(bachelors_puma_se, black_puma_se, hispanic_puma_se, inctot_puma,
#                      log_inctot_puma_se, owned_puma_se, age_puma_se, immigrant_puma,
#                      poverty_100_puma_se, poverty_200_puma_se, hwsei_puma_se, 
#                      unemployed_puma_se, valueh_puma,
#                      rent_puma_se, costelec_puma_se, density, pctmetro),
#             ~ sqrt(sum(perwt*(.x^2), na.rm = T)/sum(perwt, na.rm = T)^2)
#   ))
            #~ sqrt(survey_mean(.x^2, na.rm = T)/n())))

sample_size <- all_geo %>%
  filter(married == T & year >= 2012) %>%
  group_by(group) %>%
  summarize(n = n(),
            n_weighted = sum(perwt))


desc_tab_ind <- read_csv(here('geo/files', 'desc_tab_ind_married.csv'))

FitFlextableToPage <- function(ft, pgwidth = 6){
  ft_out <- ft %>% flextable::autofit()
  ft_out <- flextable::width(ft_out, width = dim(ft_out)$widths*pgwidth /
                               (flextable::flextable_dim(ft_out)$widths))
  return(ft_out)
}

# desc_tab_ind %>%
#   rename_with(~ paste0(.x, '_coef'), !ends_with('_se')) %>%
#   pivot_longer(-group_coef, names_sep = '_')


desc_tab_ind %>%
  left_join(sample_size) %>%
  column_to_rownames('group') %>%
  t() %>%
  as.data.frame() %>%
  # mutate(`Different-sex, immigrant` = round(V1, 3), `Same-sex, immigrant` = round(V2, 3),
  #        `Same-sex, non-immigrant` = round(V3, 3)) %>%
  # select(different_sex, same_sex) %>%
  rownames_to_column('Variable') %>%
  # mutate(Variable = ifelse(str_detect(Variable, '_se'), Variable, paste0(Variable, '_coef'))) %>%
  # pivot_wider(names_from = Variable, names_sep = '_')
  filter(!str_detect(Variable, '_se')) %>%
  mutate(Variable = recode(Variable, !!!variable_names_swap)) %>%
  flextable() %>% 
  colformat_double(i = 15:16, digits = 0) %>%
  FitFlextableToPage() %>% # flextable::autofit() %>%
  flextable::set_caption('Married only: Mean values for individual variables for immigrants in different- or same-sex couples, 2012-2019 and 2021-2023. For same-sex couples, the married variable is coded as missing before 2012.') 
  # kable(booktabs = T, linesep = '', caption = 'Mean values for geographic variables for immigrants in different- or same-sex couples, 2008-2023')


```

\newpage

```{r desc-geo-married}

# desc_tab_se <- immigrants_survey %>%
#   group_by(same_sex) %>%
#   summarize(across(c(bachelors_puma_se, black_puma_se, hispanic_puma_se, inctot_puma,
#                      log_inctot_puma_se, owned_puma_se, age_puma_se, immigrant_puma,
#                      poverty_100_puma_se, poverty_200_puma_se, hwsei_puma_se, 
#                      unemployed_puma_se, valueh_puma,
#                      rent_puma_se, costelec_puma_se, density, pctmetro),
#             ~ sqrt(sum(perwt*(.x^2), na.rm = T)/sum(perwt, na.rm = T)^2)
#   ))
            #~ sqrt(survey_mean(.x^2, na.rm = T)/n())))



desc_tab <- read_csv(here('geo/files', 'desc_tab_married.csv'))

FitFlextableToPage <- function(ft, pgwidth = 6){
  ft_out <- ft %>% flextable::autofit()
  ft_out <- flextable::width(ft_out, width = dim(ft_out)$widths*pgwidth /
                               (flextable::flextable_dim(ft_out)$widths))
  return(ft_out)
}

desc_tab %>%
  select(group, inctot_puma, unemployed_puma, hwsei_puma, valueh_puma,
         bachelors_puma, black_puma, hispanic_puma, immigrant_puma, 
         density, state_policy, lgbt_nonprofits, immigrant_nonprofits) %>%
  left_join(sample_size) %>%
  column_to_rownames('group') %>%
  t() %>%
  as.data.frame() %>%
  # mutate(`Different-sex, immigrant` = round(V1, 3), `Same-sex, immigrant` = round(V2, 3),
  #        `Same-sex, non-immigrant` = round(V3, 3)) %>%
  # select(different_sex, same_sex) %>%
  rownames_to_column('Variable') %>%
  # filter(!str_detect(Variable, '_se')) %>%
  mutate(Variable = recode(Variable, !!!variable_names_swap)) %>%
  flextable() %>% 
  colformat_double(i = 13:14, digits = 0) %>%
  FitFlextableToPage() %>% # flextable::autofit() %>%
  flextable::set_caption('Married only: Mean values for geographic variables for immigrants in different- or same-sex couples, 2008-2023') 
  # kable(booktabs = T, linesep = '', caption = 'Only married: Mean values for geographic variables for immigrants in different- or same-sex couples, 2012-2019 and 2021-2023')


```


