---
title: "Same-Sex Immigrant Couples"
subtitle: "ACS Exploratory Analysis"
date: "8/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, cache = F,
                      cache.lazy = FALSE)

library(RColorBrewer)
library(haven)
library(cowplot)
library(srvyr)
library(here)
library(tidyverse)

# theme_set(theme_cowplot(font_family = 'Palatino') + 
theme_set(theme_classic() + 
            theme(#legend.title=element_blank(), 
                  panel.grid.major.y = element_line('grey80'),
                  legend.background = element_rect(fill = "transparent")))
ggplot <- function(...) ggplot2::ggplot(...) #+ scale_color_brewer(palette="Dark2")

options(scipen=999)
```

```{r load}
top_countries <- read_csv(here('data', 'top_countries.csv')) %>%
  pull(1)
# top_countries <- c("Mexico", "India",  "Philippines", "China",              "El Salvador", "Vietnam",
#                    "Cuba",               "Korea",              "Dominican Republic", "Guatemala" ) 
acs_wide <- read_csv(here('data', 'acs_wide.csv'))
acs_oneimm <- read_csv(here('data', 'acs_oneimm.csv'))

# acs_wide2 <- acs_wide
# acs_oneimm2 <- acs_oneimm
```

```{r plots}
# set survey design
# acs_design <- as_survey_design(
#   .data = acs_wide,
#   ids = cluster,
#   strata = strata,
#   weights = hhwt)

# Married and unmarried same-sex couples over time
acs_wide %>%
  filter(same_sex == T, imm_couple != "none") %>%
  group_by(year, imm_couple, related_partner) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, color = imm_couple)) +
  geom_line() + geom_point() + facet_wrap(~related_partner)
  ggtitle('Married and unmarried same-sex couples over time')

# By sex
acs_wide %>%
  filter(same_sex == T, imm_couple != "none") %>%
  mutate(sex_main = as_factor(sex_main)) %>%
  group_by(year, imm_couple, sex_main) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, color = imm_couple)) +
  geom_line() + geom_point() +
  facet_wrap(~sex_main) +
  ggtitle('Same-sex couples by sex')

# By relation
acs_wide %>%
  filter(same_sex == T, imm_couple != "none") %>%
  group_by(year, imm_couple, related_partner) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, color = imm_couple)) +
  geom_line() + geom_point() +
  facet_wrap(~related_partner) +
  ggtitle('Same-sex couples with immigrants, by relation')

# Comparing same-sex and non
acs_wide %>%
  filter(imm_couple != "none") %>%
  mutate(same_sex = ifelse(same_sex == T, 'Same-Sex', 'Different-Sex')) %>%
  group_by(year, imm_couple, same_sex) %>%
  count(wt = hhwt) %>%
  mutate(`Total population (thousands)` = n/1000,
         Year = year) %>%
  # summarize(n = survey_total())
  ggplot(aes(x = Year, y = `Total population (thousands)`, color = imm_couple)) +
  geom_line() + geom_point() +
  facet_wrap(~same_sex, scales = "free") +
  labs(color = 'Number of immigrants\nin couple') +
  xlim(2007, 2019) +
  theme(legend.position=c(.15,.35))
  # ggtitle('Total couples with immigrants')
  
 ggsave('same_opp.jpg', width = 6, height = 3)



acs_oneimm %>%
  filter(bpld_immigrant %in% top_countries[1:10]) %>%
  mutate(country = as_factor(bpld_immigrant)) %>%
  filter(same_sex == T) %>%
  group_by(year, country, relation) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, color = country)) +
  geom_line() +
  facet_wrap(~relation) +
  ggtitle('Top ten countries of origin for same-sex couples')

```


# Conditional statistics
All figures contain only couples with one immigrant and one non-immigrant. The each compare the trends for opposite-sex couples to same-sex couples, aggregating "married" and "unmarried partner" categories. Unless otherwise stated, all characteristics describe the immigrant in the couple.
```{r cond-plots}
acs_oneimm <- acs_oneimm %>%
  mutate(same_sex = case_when(
    same_sex == T ~ 'Same-sex',
    same_sex == F ~ 'Opposite-sex'
  ))

acs_oneimm %>%
  group_by(year, same_sex) %>%
  summarize(inctot_immigrant = weighted.mean(inctot_immigrant, w = hhwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = inctot_immigrant)) +
  geom_line() +
  facet_wrap(~same_sex) +
  ggtitle('Total Income')

acs_oneimm %>%
  group_by(year, same_sex) %>%
  summarize(ftotinc = weighted.mean(ftotinc, w = hhwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = ftotinc)) +
  geom_line() +
  facet_wrap(~same_sex) +
  ggtitle('Household Income')

acs_oneimm %>%
  group_by(year, same_sex) %>%
  summarize(occscore_immigrant = weighted.mean(occscore_immigrant, w = hhwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = occscore_immigrant)) +
  geom_line() +
  facet_wrap(~same_sex) +
  ggtitle('Occupational Score')

acs_oneimm %>%
  group_by(year, same_sex) %>%
  summarize(hwsei_immigrant = weighted.mean(hwsei_immigrant, w = hhwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = hwsei_immigrant)) +
  geom_line() +
  facet_wrap(~same_sex) +
  ggtitle('Hauser-Warren SEI Score')

acs_oneimm %>%
  group_by(year, same_sex) %>%
  summarize(yrimmig_immigrant = weighted.mean(yrimmig_immigrant, w = hhwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = yrimmig_immigrant)) +
  geom_line() +
  facet_wrap(~same_sex) +
  ggtitle('Year of immigration')

# Categorical variables
acs_oneimm %>%
  group_by(year, same_sex, educ_immigrant) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, fill = educ_immigrant)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Education')

acs_oneimm %>%
  mutate(metro = recode(metro,
    "In metropolitan area: Central/principal city status indeterminable (mixed)" = "In metro (mixed)",
    "In metropolitan area: Not in central/principal city" = "In metro (not center)",
    "In metropolitan area: In central/principal city" = "In metro (center)",                    
    "Not in metropolitan area" = "Not in metro", 
    "Metropolitan status indeterminable (mixed)" = "Mixed")) %>%
  group_by(year, same_sex, metro) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, fill = metro)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Metro')

acs_oneimm %>%
  group_by(year, same_sex, empstat_immigrant) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, fill = empstat_immigrant)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Employment Status')

acs_oneimm %>%
  group_by(year, same_sex, region) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, fill = region)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Region')

acs_oneimm %>%
  group_by(year, same_sex, nchild) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, fill = nchild)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Number of children present')

acs_oneimm %>%
  filter(bpld_immigrant %in% top_countries[1:10]) %>%
  group_by(year, same_sex, bpld_immigrant) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, fill = bpld_immigrant)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Immigrant birthplace')

acs_wide %>% filter(same_sex == T & imm_couple != 'none') %>% count()
nrow(acs_oneimm)
```




