---
title: "Same-Sex Immigrant Couples"
subtitle: "Descriptive Statistics"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  bookdown::pdf_document2:
    toc: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, cache = T,
                      cache.lazy = FALSE)

library(RColorBrewer)
library(haven)
library(cowplot)
library(srvyr)
library(here)
library(OasisR)
library(tidyverse)

# theme_set(theme_cowplot(font_family = 'Palatino') + 
theme_set(theme_classic() + 
            theme(#legend.title=element_blank(), 
                  panel.grid.major.y = element_line('grey80'),
                  legend.background = element_rect(fill = "transparent")))
ggplot <- function(...) ggplot2::ggplot(...) #+ scale_color_brewer(palette="Dark2")

options(scipen=999)
```

```{r load}
top_countries <- read_csv(here('data', 'top_countries.csv')) %>%
  pull(1)
acs_wide <- read_csv(here('data', 'acs_wide.csv'))
# acs_oneimm <- read_csv(here('data', 'acs_oneimm.csv'))
acs_coupled_imms <- read_csv(here('data', 'acs_coupled_imms.csv'))
acs_dyad <- read_csv(here('data', 'acs_dyad.csv'))


acs_coupled_imms <- acs_coupled_imms %>%
  mutate(same_sex = ifelse(same_sex == T, 'Same Sex', 'Different Sex')) 

```

# Scale of migration
## Different- and same-sex couples containing one or two immigrants
```{r}
acs_wide %>%
  filter(imm_couple != "none") %>%
  mutate(same_sex = ifelse(same_sex == T, 'Same-Sex', 'Different-Sex')) %>%
  group_by(year, imm_couple, same_sex) %>%
  count(wt = hhwt) %>%
  mutate(`Total population (thousands)` = n/1000,
         Year = year) %>%
  # summarize(n = survey_total())
  ggplot(aes(x = Year, y = `Total population (thousands)`, color = imm_couple)) +
  geom_line() +
  facet_wrap(~same_sex, scales = "free") +
  labs(color = 'Number of immigrants\nin couple') +
  xlim(2007, 2019) +
  theme(legend.position=c(.15,.35))
  # ggtitle('Total couples with immigrants')
```

## Married and unmarried same-sex couples over time
```{r}
acs_wide %>%
  filter(same_sex == T, imm_couple != "none") %>%
  group_by(year, imm_couple, related_partner) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, color = imm_couple)) +
  geom_line() + 
  facet_wrap(~related_partner) +
  xlim(2007, 2019)
```

## Immigrants within last year
```{r}
acs_wide %>%
  filter(imm_couple != "none") %>%
  filter(year - yrimmig_partner <= 1 | year - yrimmig_main <= 1) %>%
  mutate(same_sex = ifelse(same_sex == T, 'Same-Sex', 'Different-Sex')) %>%
  group_by(year, imm_couple, same_sex) %>%
  count(wt = hhwt) %>%
  mutate(`Total population (thousands)` = n/1000,
         Year = year) %>%
  # summarize(n = survey_total())
  ggplot(aes(x = Year, y = `Total population (thousands)`, color = imm_couple)) +
  geom_line() +
  facet_wrap(~same_sex, scales = "free") +
  labs(color = 'Number of immigrants\nin couple') +
  xlim(2007, 2019) +
  theme(legend.position=c(.15,.35))
```



# Differences in characteristics between immigrants in same- and opposite-sex couples
## Citizenship
```{r}
acs_coupled_imms %>%
  mutate(citizen = (citizen == 'Naturalized citizen')) %>%
  group_by(year, same_sex) %>%
  summarize(citizen = weighted.mean(citizen, w = perwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = citizen)) +
  geom_line() +
  facet_wrap(~same_sex) +
  ggtitle('Proportion naturalized')

```

## Employment
```{r}
acs_coupled_imms %>%
  group_by(year, same_sex) %>%
  summarize(inctot = weighted.mean(inctot, w = perwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = inctot)) +
  geom_line() +
  facet_wrap(~same_sex) +
  ggtitle('Individual Total Income')

acs_wide %>%
  filter(imm_couple != 'none') %>%
  group_by(year, same_sex) %>%
  summarize(ftotinc = weighted.mean(ftotinc, w = hhwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = ftotinc)) +
  geom_line() +
  facet_wrap(~same_sex) +
  ggtitle('Family Income')

acs_coupled_imms %>%
  group_by(year, same_sex) %>%
  summarize(occscore = weighted.mean(occscore, w = perwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = occscore)) +
  geom_line() +
  facet_wrap(~same_sex) +
  ggtitle('Occupational Score')

acs_coupled_imms %>%
  group_by(year, same_sex, empstat) %>%
  count(wt = perwt) %>%
  ggplot(aes(x = year, y = n, fill = empstat)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Employment Status')
```



## Years in US
```{r}
acs_coupled_imms %>%
  ggplot(aes(x = years_in_us)) +
  geom_histogram() +
  facet_wrap(~same_sex, scales = 'free', nrow = 2) +
  ggtitle('Years in US')

# acs_coupled_imms %>%
#   ggplot(aes(x = years_in_us)) +
#   geom_histogram() +
#   facet_wrap(~same_sex + year, scales = 'free') +
#   ggtitle('Years in US')

acs_coupled_imms %>%
  group_by(year, same_sex) %>%
  summarize(years_in_us = weighted.mean(years_in_us, w = perwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = years_in_us)) +
  geom_line() +
  facet_wrap(~same_sex) +
  ggtitle('Years in US')


```

## Education
```{r}
acs_coupled_imms %>%
  group_by(year, same_sex, educ) %>%
  count(wt = perwt) %>%
  ggplot(aes(x = year, y = n, fill = educ)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Education')
```


## Region
```{r}
acs_coupled_imms %>%
  mutate(metro = recode(metro,
    "In metropolitan area: Central/principal city status indeterminable (mixed)" = "In metro (mixed)",
    "In metropolitan area: Not in central/principal city" = "In metro (not center)",
    "In metropolitan area: In central/principal city" = "In metro (center)",                    
    "Not in metropolitan area" = "Not in metro", 
    "Metropolitan status indeterminable (mixed)" = "Mixed")) %>%
  group_by(year, same_sex, metro) %>%
  count(wt = perwt) %>%
  ggplot(aes(x = year, y = n, fill = metro)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Metro')

acs_coupled_imms %>%
  group_by(year, same_sex, region) %>%
  count(wt = perwt) %>%
  ggplot(aes(x = year, y = n, fill = region)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Region')


acs_dyad %>%
  select(same_sex_stock, opp_sex_stock, year) %>%
  group_by(year) %>%
  summarize(dissimilarity = 
              DIDuncan(data.frame(same_sex_stock, opp_sex_stock))[1,2]) %>%
  ggplot(aes(x = year, y = dissimilarity)) +
  geom_line() +
  ggtitle('Dissimilarity index for same- and different-sex immigrant couples by state and birthplace')



```

## Family
```{r}
acs_wide %>%
  filter(imm_couple != 'none') %>%
  group_by(year, same_sex, nchild) %>%
  count(wt = hhwt) %>%
  ggplot(aes(x = year, y = n, fill = as.factor(nchild))) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Number of children present')

acs_wide %>%
  filter(imm_couple != 'none') %>%
  group_by(year, same_sex) %>%
  summarize(nchild = weighted.mean(nchild, w = hhwt, na.rm = T)) %>%
  ggplot(aes(x = year, y = nchild, col = same_sex)) +
  geom_line() +
  ggtitle('Average number of children')

acs_coupled_imms %>%
  filter(bpld %in% top_countries[1:10]) %>%
  group_by(year, same_sex, bpld) %>%
  count(wt = perwt) %>%
  ggplot(aes(x = year, y = n, fill = bpld)) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~same_sex) +
  ggtitle('Immigrant birthplace')


```









